Proper error channel.

diff --git a/etc/settings b/etc/settings
--- a/etc/settings
+++ b/etc/settings
@@ -9,7 +9,7 @@ fi
 NAPROCHE_EXE_DIR="$NAPROCHE_HOME/${ISABELLE_WINDOWS_PLATFORM64:-$ISABELLE_PLATFORM64}"
 NAPROCHE_EXE="$NAPROCHE_EXE_DIR/Naproche-SAD"
 if [ ! -f "$NAPROCHE_EXE" ]; then
-  echo "### Missing executable program: $NAPROCHE_EXE"
+  echo >&2 "### Missing executable program: $NAPROCHE_EXE"
 fi
 
 NAPROCHE_JAR="$NAPROCHE_HOME/Isabelle/naproche.jar"
@@ -17,5 +17,5 @@ if [ -f "$NAPROCHE_JAR" ]; then
   classpath "$NAPROCHE_JAR"
   isabelle_scala_service "isabelle.naproche.File_Format"
 else
-  echo "### Missing Isabelle/Scala module: $NAPROCHE_JAR"
+  echo >&2 "### Missing Isabelle/Scala module: $NAPROCHE_JAR"
 fi
